# Generated by Django 5.2.4 on 2025-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('sportswear', 'Sportswear'), ('footwear', 'Footwear')], default='men', max_length=20),
        ),
    ]
