# Generated by Django 5.2.4 on 2025-10-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_address_order_orderitem_orderupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_deliver_order', 'Can deliver assigned orders'), ('can_manage_orders', 'Can manage all orders')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_manage_products', 'Can manage products')]},
        ),
    ]
