# Generated by Django 5.2.4 on 2025-12-26 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_address_is_confirmed_address_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'street', 'city', 'state', 'pincode')},
        ),
    ]
